/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-02 14:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/1-1Pizza/Pizza1.html", Long.valueOf(1580654941557L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../../js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    #dateSlot{color: pink;}\r\n");
      out.write("    table{width: 500px; height: 500px;\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            text-align: center;}\r\n");
      out.write("    td, th{border: 1px solid black;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h1>ì¤ëì <span id=\"dateSlot\"></span> ìëë¤.</h1>\r\n");
      out.write("    <h1>í¼ì ìì¹´ë°ë¯¸</h1>\r\n");
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>ì¢ë¥</th>\r\n");
      out.write("            <th>ì´ë¦</th>\r\n");
      out.write("            <th>ê°ê²©</th>\r\n");
      out.write("            <th rowspan=\"12\">&nbsp;</th>\r\n");
      out.write("            <th>ì¢ë¥</th>\r\n");
      out.write("            <th>ì´ë¦</th>\r\n");
      out.write("            <th>ê°ê²©</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"5\">í¼ì</td>\r\n");
      out.write("            <td>ì¹ì¦í¼ì</td>\r\n");
      out.write("            <td>5000</td>\r\n");
      out.write("            <td rowspan=\"11\">ì¬ì´ë</td>\r\n");
      out.write("            <td>ì¤ë¸êµ¬ì´íµë­</td>\r\n");
      out.write("            <td>9000</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ì½¤ë¹ë¤ì´ìí¼ì</td>\r\n");
      out.write("            <td>6000</td>\r\n");
      out.write("            <td>ì¹í¨ì¤í±&ì</td>\r\n");
      out.write("            <td>4900</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>í¬íì´í í¼ì</td>\r\n");
      out.write("            <td>7000</td>\r\n");
      out.write("            <td>ì¹ì¦ì¤ë¸ì¤íê²í°</td>\r\n");
      out.write("            <td>4000</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ê³ êµ¬ë§í¼ì</td>\r\n");
      out.write("            <td>7000</td>\r\n");
      out.write("            <td>ìì°ë§&ì¨ì§ê°ì</td>\r\n");
      out.write("            <td>3500</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ë¶ê³ ê¸°í¼ì</td>\r\n");
      out.write("            <td>8000</td>\r\n");
      out.write("            <td>ê°ë¦­í¬íì´í </td>\r\n");
      out.write("            <td>3500</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"6\">í í</td>\r\n");
      out.write("            <td>ê³ êµ¬ë§ë¬´ì¤</td>\r\n");
      out.write("            <td>1000</td>\r\n");
      out.write("            <td>ì½ë¼</td>\r\n");
      out.write("            <td>1500</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ì½í¬ë¦¼ë¬´ì¤</td>\r\n");
      out.write("            <td>1500</td>\r\n");
      out.write("            <td>ì¬ì´ë¤</td>\r\n");
      out.write("            <td>1500</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>íì¸ì íí í</td>\r\n");
      out.write("            <td>2000</td>\r\n");
      out.write("            <td>ê°ë¦­ìì¤</td>\r\n");
      out.write("            <td>500</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ì¹ì¦í í</td>\r\n");
      out.write("            <td>2000</td>\r\n");
      out.write("            <td>í¼í´</td>\r\n");
      out.write("            <td>300</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ì¹ì¦í¬ë¬ì¤í¸</td>\r\n");
      out.write("            <td>2000</td>\r\n");
      out.write("            <td>í«ìì¤</td>\r\n");
      out.write("            <td>100</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>ì¹ì¦ë°ì´í¸</td>\r\n");
      out.write("            <td>3000</td>\r\n");
      out.write("            <td>íë§ì° ì¹ì¦ê°ë£¨</td>\r\n");
      out.write("            <td>100</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"/00_Assignment/orderCheck.go\" method=\"GET\">\r\n");
      out.write("        <label>í¼ì : </label>\r\n");
      out.write("        <select name=\"pizza\">\r\n");
      out.write("            <option value=\"ì¹ì¦í¼ì,5000\">ì¹ì¦í¼ì</option>\r\n");
      out.write("            <option value=\"ì½¤ë¹ë¤ì´ìí¼ì,6000\">ì½¤ë¹ë¤ì´ìí¼ì</option>\r\n");
      out.write("            <option value=\"í¬íì´í í¼ì,7000\">í¬íì´í í¼ì</option>\r\n");
      out.write("            <option value=\"ê³ êµ¬ë§í¼ì,7000\">ê³ êµ¬ë§í¼ì</option>\r\n");
      out.write("            <option value=\"ë¶ê³ ê¸°í¼ì,8000\">ë¶ê³ ê¸°í¼ì</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>í í : </label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"topping\" value=\"ê³ êµ¬ë§ë¬´ì¤,1000\">ê³ êµ¬ë§ë¬´ì¤ \r\n");
      out.write("        <input type=\"checkbox\" name=\"topping\" value=\"ì½í¬ë¦¼ë¬´ì¤,1500\">ì½í¬ë¦¼ë¬´ì¤ \r\n");
      out.write("        <input type=\"checkbox\" name=\"topping\" value=\"íì¸ì íí í,2000\">íì¸ì íí í \r\n");
      out.write("        <input type=\"checkbox\" name=\"topping\" value=\"ì¹ì¦í í,2000\">ì¹ì¦í í \r\n");
      out.write("        <input type=\"checkbox\" name=\"topping\" value=\"ì¹ì¦í¬ë¬ì¤í¸,2000\">ì¹ì¦í¬ë¬ì¤í¸ \r\n");
      out.write("        <input type=\"checkbox\" name=\"topping\" value=\"ì¹ì¦ë°ì´í¸,3000\">ì¹ì¦ë°ì´í¸\r\n");
      out.write("        <br>\r\n");
      out.write("        <label>ì¬ì´ë : </label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ì¤ë¸êµ¬ì´íµë­,9000\">ì¤ë¸êµ¬ì´íµë­ \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ì¹í¨ì¤í±&ì,4900\">ì¹í¨ì¤í±&ì \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ì¹ì¦ì¤ë¸ì¤íê²í°,4000\">ì¹ì¦ì¤ë¸ì¤íê²í° \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ìì°ë§&ì¨ì§ê°ì,3500\">ìì°ë§&ì¨ì§ê°ì \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ê°ë¦­í¬íì´í ,3000\">ê°ë¦­í¬íì´í  \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ì½ë¼,1500\">ì½ë¼ \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ì¬ì´ë¤,1500\">ì¬ì´ë¤ \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"ê°ë¦­ìì¤,500\">ê°ë¦­ìì¤ \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"í¼í´,300\">í¼í´ \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"í«ìì¤,100\">í«ìì¤ \r\n");
      out.write("        <input type=\"checkbox\" name=\"side\" value=\"íë§ì° ì¹ì¦ê°ë£¨,100\">íë§ì° ì¹ì¦ê°ë£¨ \r\n");
      out.write("        <br>\r\n");
      out.write("        <button type=\"submit\">íì¸</button>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("            var dt = new Date();\r\n");
      out.write("\r\n");
      out.write("            var recentYear = dt.getFullYear();\r\n");
      out.write("            var recentMonth = dt.getMonth() + 1;\r\n");
      out.write("            var recentDay = dt.getDate();\r\n");
      out.write("            var recentday = dt.getDay();\r\n");
      out.write("            console.log(recentday);\r\n");
      out.write("            var week = ['ì¼ìì¼','ììì¼','íìì¼','ììì¼','ëª©ìì¼','ê¸ìì¼','í ìì¼'];\r\n");
      out.write("            var today = recentYear+'ë '+recentMonth+'ì '+recentDay+'ì¼ '+week[recentday];\r\n");
      out.write("            console.log(today);\r\n");
      out.write("\r\n");
      out.write("            $('#dateSlot').html(today);\r\n");
      out.write("            \r\n");
      out.write("            console.log($('select>option:first').val());\r\n");
      out.write("\r\n");
      out.write("            $('form').submit(function(){\r\n");
      out.write("            })\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
